# Form implementation generated from reading ui file 'design/saved_data_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.type_box = QtWidgets.QFormLayout()
        self.type_box.setObjectName("type_box")
        self.type_label = QtWidgets.QLabel(self.centralwidget)
        self.type_label.setObjectName("type_label")
        self.type_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.type_label)
        self.type_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.type_combobox.setObjectName("type_combobox")
        self.type_combobox.addItem("")
        self.type_combobox.addItem("")
        self.type_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.type_combobox)
        self.gridLayout.addLayout(self.type_box, 0, 0, 1, 1)
        self.date_box = QtWidgets.QFormLayout()
        self.date_box.setObjectName("date_box")
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setObjectName("date_label")
        self.date_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.date_label)
        self.date_input = QtWidgets.QDateEdit(self.centralwidget)
        self.date_input.setObjectName("date_input")
        self.date_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.date_input)
        self.gridLayout.addLayout(self.date_box, 0, 1, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 0, 2, 1, 1)
        self.data_table = QtWidgets.QTableWidget(self.centralwidget)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.gridLayout.addWidget(self.data_table, 1, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saved Data VIewer"))
        self.type_label.setText(_translate("MainWindow", "Type"))
        self.type_combobox.setItemText(0, _translate("MainWindow", "Transmit Terminal"))
        self.type_combobox.setItemText(1, _translate("MainWindow", "Ethernet Communication"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.search_button.setText(_translate("MainWindow", "Search"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
