# Form implementation generated from reading ui file 'design/saved_data_window.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(657, 498)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.type_box = QtWidgets.QFormLayout()
        self.type_box.setObjectName("type_box")
        self.type_label = QtWidgets.QLabel(Dialog)
        self.type_label.setObjectName("type_label")
        self.type_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.type_label)
        self.type_comboBox = QtWidgets.QComboBox(Dialog)
        self.type_comboBox.setObjectName("type_comboBox")
        self.type_comboBox.addItem("")
        self.type_comboBox.addItem("")
        self.type_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.type_comboBox)
        self.gridLayout.addLayout(self.type_box, 0, 0, 1, 1)
        self.date_box = QtWidgets.QFormLayout()
        self.date_box.setObjectName("date_box")
        self.date_label = QtWidgets.QLabel(Dialog)
        self.date_label.setObjectName("date_label")
        self.date_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.date_label)
        self.date_input = QtWidgets.QDateEdit(Dialog)
        self.date_input.setObjectName("date_input")
        self.date_box.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.date_input)
        self.gridLayout.addLayout(self.date_box, 0, 2, 1, 1)
        self.search_button = QtWidgets.QPushButton(Dialog)
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 0, 3, 1, 1)
        self.data_tableWidget = QtWidgets.QTableWidget(Dialog)
        self.data_tableWidget.setObjectName("data_tableWidget")
        self.data_tableWidget.setColumnCount(0)
        self.data_tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.data_tableWidget, 1, 0, 1, 4)
        self.gridLayout.setColumnStretch(0, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Saved Data Viewer"))
        self.type_label.setText(_translate("Dialog", "Type"))
        self.type_comboBox.setItemText(0, _translate("Dialog", "Transmit Terminal"))
        self.type_comboBox.setItemText(1, _translate("Dialog", "Ethernet Communication"))
        self.date_label.setText(_translate("Dialog", "Date"))
        self.search_button.setText(_translate("Dialog", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
